name: Build APK

on:
  push:
    branches:
      - main  # Trigger the build when pushing to the main branch

jobs:
  build:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner

    steps:
      # Check out the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up JDK 11
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'zulu'   # Use zulu for Java 11

      # Install dependencies
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y openjdk-11-jdk
          sudo apt-get install -y android-sdk

      # Set up Android SDK
      - name: Set up Android SDK
        run: |
          mkdir -p $HOME/.android
          echo "sdk.dir=$HOME/.android/sdk" > $HOME/.android/local.properties
          curl -sSL https://dl.google.com/android/repository/commandlinetools-linux-8512546_latest.zip -o commandlinetools.zip
          unzip commandlinetools.zip -d $HOME/.android
          yes | $HOME/.android/cmdline-tools/bin/sdkmanager --sdk_root=$HOME/.android --licenses
          $HOME/.android/cmdline-tools/bin/sdkmanager --sdk_root=$HOME/.android --update
          $HOME/.android/cmdline-tools/bin/sdkmanager --sdk_root=$HOME/.android "platforms;android-30" "build-tools;30.0.3" "tools"


      # Build the APK
      - name: Build APK
        run: |
          cd android
          ./gradlew assembleRelease

      # Upload the APK as an artifact
      - name: Upload APK as artifact
        uses: actions/upload-artifact@v3
        with:
          name: MyApp-release
          path: android/app/build/outputs/apk/release/app-release.apk
